'use strict';

/* --------------------------------------------------------------------------
   Configuración
   -------------------------------------------------------------------------- */
const CONFIG = { foodThreshold: 0.20, jpegQuality: 0.70, maxSize: 800 };
const FOOD_STRONG = ['pizza','cheeseburger','hotdog','burrito','taco','sandwich','bagel','pretzel','French loaf','dough','guacamole','carbonara','spaghetti','meat loaf','potpie','hot pot','consomme','trifle','ice cream','mashed potato','cauliflower','broccoli','zucchini','acorn squash','butternut squash','spaghetti squash','cucumber','artichoke','bell pepper','head cabbage','cardoon','mushroom','ear of corn','Granny Smith','apple','orange','lemon','banana','pineapple','strawberry','pomegranate','fig','jackfruit','custard apple','bakery','confectionery','French fries','sushi','rice','pasta','noodle','steak','chicken','fish','shrimp','lobster','crab','egg','omelette','salad','soup','stew','curry','cake','pie','cookie','waffle','pancake','burger','kebab','paella','tortilla','bread','cheese','meat','seafood','dessert','fruit','vegetable','food','dish','meal'];
const FOOD_CONTEXT = ['plate','soup bowl','mixing bowl','bowl','tray','platter','dining table','restaurant','menu','wok','frying pan','skillet','saucepan','Dutch oven','caldron','spatula','ladle','wooden spoon','table knife','fork','spoon','napkin','tablecloth','cup','coffee mug','goblet','beer glass','wine bottle','espresso','coffeepot','teapot'];
const NON_FOOD = ['person','face','laptop','notebook','computer','keyboard','mouse','cellular telephone','iPod','television','monitor','screen','car','sports car','bicycle','motor scooter','dog','cat','bird','horse','sheep','book','jigsaw puzzle','envelope','wallet','purse','backpack','sunglasses','sunglass','shoe','sandal','running shoe','jean','suit','sweatshirt','jersey','lamp','table lamp','candle','vase','flowerpot','window screen','sliding door','bookcase','wardrobe','chair','rocking chair','sofa','studio couch','bed','quilt','pillow','remote control','digital watch','analog clock','wall clock','toilet','washbasin','ashcan','street sign','traffic light','mountain','seashore','lakeside','valley','tree','flower','daisy','building','castle','church'];

/* Estado */
let model = null;
let stream = null;
let animationFrame = null;
let cameraActive = false;

/* Utilidades DOM */
const $ = (id) => document.getElementById(id);
const els = { stage:$('stage'), video:$('video'), overlay:$('overlay'), result:$('result'), loader:$('loader'), capture:$('capture'), closeCamera:$('closeCamera'), error:$('error'), decision:$('decision'), size:$('size'), log:$('log'), modelStatus:$('modelStatus'), statusDetail:$('statusDetail') };

/* Logging */
function log(message, replace = false) { const stamp = new Date().toLocaleTimeString('es-ES'); els.log.textContent = replace ? message : `${els.log.textContent}\n[${stamp}] ${message}`; els.log.scrollTop = els.log.scrollHeight; }
function showError(message) { els.error.textContent = message; els.error.hidden = false; }
function clearError() { els.error.hidden = true; els.error.textContent = ''; }
function setLoading(active) { els.loader.hidden = !active; }
function configFromControls() { return { foodThreshold:Number($('foodThreshold').value), jpegQuality:Number($('jpegQuality').value), maxSize:Number($('maxSize').value) }; }

/* Overlay circular */
function drawOverlay() { if (!cameraActive) return; const canvas = els.overlay; const width = canvas.clientWidth || els.stage.clientWidth; const height = canvas.clientHeight || els.stage.clientHeight; const dpr = window.devicePixelRatio || 1; canvas.width = width*dpr; canvas.height = height*dpr; const ctx = canvas.getContext('2d'); ctx.scale(dpr,dpr); const radius = Math.min(width,height)*0.37; const cx = width/2; const cy = height/2; ctx.fillStyle = 'rgba(5, 10, 8, .68)'; ctx.fillRect(0,0,width,height); ctx.globalCompositeOperation = 'destination-out'; ctx.beginPath(); ctx.arc(cx,cy,radius,0,Math.PI*2); ctx.fill(); ctx.globalCompositeOperation = 'source-over'; ctx.strokeStyle = '#d8ef57'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(cx,cy,radius,0,Math.PI*2); ctx.stroke(); animationFrame = requestAnimationFrame(drawOverlay); }

/* Cámara */
function stopCamera() { cameraActive = false; if (animationFrame) cancelAnimationFrame(animationFrame); animationFrame = null; if (stream) stream.getTracks().forEach(track => track.stop()); stream = null; els.video.pause(); els.video.srcObject = null; els.video.hidden = true; els.overlay.hidden = true; els.capture.hidden = true; els.closeCamera.hidden = true; els.result.hidden = true; els.result.removeAttribute('src'); els.stage.classList.add('empty'); }
async function openCamera() { clearError(); stopCamera(); try { stream = await navigator.mediaDevices.getUserMedia({ video:{ facingMode:{ exact:'environment' } }, audio:false }); } catch (firstError) { try { stream = await navigator.mediaDevices.getUserMedia({ video:{ facingMode:'user' }, audio:false }); } catch (error) { showError('No se pudo acceder a la cámara. Revisa los permisos del navegador.'); log(`Cámara: ${error.message}`); return; } } cameraActive = true; els.video.srcObject = stream; els.video.hidden = false; els.overlay.hidden = false; els.capture.hidden = false; els.closeCamera.hidden = false; els.stage.classList.remove('empty'); try { await els.video.play(); } catch (error) { showError('Pulsa la pantalla para iniciar la cámara.'); els.video.addEventListener('click', () => els.video.play(), { once:true }); } drawOverlay(); }

/* Procesado de imagen */
function makeMaskedCanvas(source) { const sourceWidth = source.videoWidth || source.naturalWidth || source.width; const sourceHeight = source.videoHeight || source.naturalHeight || source.height; const side = Math.min(sourceWidth, sourceHeight); const sx = (sourceWidth-side)/2; const sy = (sourceHeight-side)/2; const canvas = document.createElement('canvas'); canvas.width = side; canvas.height = side; const ctx = canvas.getContext('2d'); ctx.fillStyle = '#080d0a'; ctx.fillRect(0,0,side,side); ctx.save(); ctx.beginPath(); ctx.arc(side/2,side/2,side/2,0,Math.PI*2); ctx.clip(); ctx.drawImage(source,sx,sy,side,side,0,0,side,side); ctx.restore(); ctx.globalCompositeOperation = 'destination-in'; ctx.beginPath(); ctx.arc(side/2,side/2,side/2,0,Math.PI*2); ctx.fill(); ctx.globalCompositeOperation = 'destination-over'; ctx.fillStyle = '#080d0a'; ctx.fillRect(0,0,side,side); return canvas; }
function resizeAndEncode(canvas) { const { maxSize, jpegQuality } = configFromControls(); const scale = Math.min(1, maxSize/canvas.width); const output = document.createElement('canvas'); output.width = Math.round(canvas.width*scale); output.height = Math.round(canvas.height*scale); output.getContext('2d').drawImage(canvas,0,0,output.width,output.height); return { dataUrl:output.toDataURL('image/jpeg',jpegQuality), quality:jpegQuality }; }

/* Clasificación */
function scorePredictions(predictions) { let strong=0, context=0, nonFood=0; predictions.forEach(({className,probability}) => { const name = className.toLowerCase(); if (FOOD_STRONG.some(k => name.includes(k.toLowerCase()))) strong += probability; if (FOOD_CONTEXT.some(k => name.includes(k.toLowerCase()))) context += probability; if (NON_FOOD.some(k => name.includes(k.toLowerCase()))) nonFood += probability; }); return { strong, context, nonFood, foodScore:strong + context*.55 - nonFood*.8 }; }
async function validateAndProcess(source) { if (!model) { showError('El modelo todavía se está cargando.'); return; } clearError(); setLoading(true); els.decision.textContent = 'ANALIZANDO…'; const masked = makeMaskedCanvas(source); try { const predictions = await model.classify(masked,15); const scores = scorePredictions(predictions); const threshold = configFromControls().foodThreshold; log(`Predicciones:\n${predictions.map(p => `• ${p.className}: ${(p.probability*100).toFixed(1)}%`).join('\n')}\n\nStrong: ${(scores.strong*100).toFixed(1)}% | Contexto: ${(scores.context*100).toFixed(1)}% | No comida: ${(scores.nonFood*100).toFixed(1)}%\nTotal: ${(scores.foodScore*100).toFixed(1)}% | Umbral: ${(threshold*100).toFixed(1)}%`, true); if (scores.foodScore < threshold) { els.decision.textContent = 'RECHAZADO'; els.size.textContent = '—'; els.result.hidden = true; els.result.removeAttribute('src'); showError('No parece haber comida suficiente en esta imagen. Prueba con un plato más centrado.'); return; } const encoded = resizeAndEncode(masked); els.result.src = encoded.dataUrl; els.result.hidden = false; els.video.hidden = true; els.overlay.hidden = true; els.decision.textContent = 'COMIDA DETECTADA'; els.size.textContent = `${(encoded.dataUrl.length*0.75/1024).toFixed(0)} KB · calidad ${(encoded.quality*100).toFixed(0)}%`; els.stage.classList.remove('empty'); } catch (error) { showError('No se pudo analizar la imagen. Inténtalo de nuevo.'); log(`Clasificación: ${error.message}`); } finally { setLoading(false); } }

/* Eventos */
function bindEvents() { $('uploadBtn').addEventListener('click', () => $('fileInput').click()); $('fileInput').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => { stopCamera(); validateAndProcess(image); URL.revokeObjectURL(url); }; image.onerror = () => { showError('No se pudo leer este archivo.'); URL.revokeObjectURL(url); }; image.src = url; event.target.value = ''; }); $('cameraBtn').addEventListener('click', openCamera); els.closeCamera.addEventListener('click', stopCamera); els.capture.addEventListener('click', () => validateAndProcess(els.video)); window.addEventListener('resize', () => { if (cameraActive) drawOverlay(); }); $('devToggle').addEventListener('click', () => { const content = $('devContent'); content.hidden = !content.hidden; $('devToggle').setAttribute('aria-expanded', String(!content.hidden)); $('devToggle').firstChild.textContent = content.hidden ? 'Abrir ajustes ' : 'Cerrar ajustes '; }); document.querySelectorAll('.dev-tab').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.dev-tab').forEach(item => item.classList.toggle('active', item === tab)); document.querySelectorAll('.dev-pane').forEach(pane => { const active = pane.dataset.pane === tab.dataset.tab; pane.classList.toggle('active',active); pane.hidden = !active; }); })); document.querySelectorAll('.step').forEach(button => button.addEventListener('click', () => { const input = $(button.dataset.target); const value = Math.min(Number(input.max),Math.max(Number(input.min),Number(input.value)+Number(button.dataset.step))); input.value = value.toFixed(input.step.includes('.') ? 2 : 0); })); $('reset').addEventListener('click', () => Object.entries(CONFIG).forEach(([key,value]) => $(key).value = value)); $('copy').addEventListener('click', async () => { const text = JSON.stringify(configFromControls(),null,2); try { await navigator.clipboard.writeText(text); log(`Configuración copiada:\n${text}`); } catch { log(`Portapapeles no disponible. Configuración:\n${text}`); } }); }

/* Init */
async function init() { bindEvents(); log('Inicializando MobileNet…', true); try { model = await mobilenet.load(); els.modelStatus.classList.add('ready'); els.statusDetail.textContent = 'MobileNet listo para clasificar'; log('Modelo cargado correctamente.'); } catch (error) { els.statusDetail.textContent = 'Error al cargar el modelo'; showError('No se pudo cargar el modelo. Comprueba tu conexión.'); log(`Carga del modelo: ${error.message}`); } }
init();
